# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: my-app
  registry: portfolioapp.azurecr.io

steps:
  - script: |
      echo "Building Docker image $(registry)/$(imageName):$(Build.BuildId)"
    displayName: 'Echo Docker Image Info'

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      Dockerfile: '**/Dockerfile'
      repository: $(registry)/$(imageName)
      tags: | 
        $(Build.BuildId)

  - script: docker images
    displayName: 'List Docker Images'

  - task: Docker@2
    displayName: 'Push image to ACR'
    inputs: 
      command: push
      repository: $(imageName)
      tags: |
        $(Build.BuildId)
      containerRegistry: 'portfolioapp-acr-connection'

  - task: AzureCLI@2
    displayName: 'Update Azure Container Instance'
    inputs:
      azureSubscription: 'AzureConnection' # tu service connection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az container update \
          --resource-group freelance-work \
          --name myportfolioapp \
          --image $(registry)/$(imageName):$(Build.BuildId)

