# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
  imageName: 'my-app'
  registry: portfolioapp.azurecr.io
   

steps:
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      Dockerfile: '**/Dockerfile'
      tags: | 
        $(Build.BuildId)
      repository: $(imageName)


  - task: Docker@2
    displayName: 'Push image to ACR'
    inputs: 
      command: push
      repository: $(imageName)
      tags: |
        $(Build.BuildId)
      containerRegistry: 'portfolioapp-acr-connection'
      
  - task: AzureCLI@2
    displayName: 'Deploy to Azure Container Instance'
    inputs:
      azureSubscription: 'AzureConnection' # Cambia esto por el nombre de tu conexión de servicio a Azure
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az container update \
          --resource-group freelance-work \
          --name myportfolioapp \
          --image portfolioapp.azurecr.io/my-app:$(Build.BuildId)

