# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'my-app'
  registry: 'portfolioapp.azurecr.io'

steps:
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      Dockerfile: '**/Dockerfile'
      repository: $(registry)/$(imageName)
      tags: | 
        $(Build.BuildId)

  - task: Docker@2
    displayName: 'Push image to ACR'
    inputs: 
      command: push
      repository: $(registry)/$(imageName)
      tags: |
        $(Build.BuildId)
      containerRegistry: 'portfolioapp-acr-connection'

