version: "3.8"

services:
  vue-app:
    container_name: portfolio-lgna
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  nginx:
    container_name: vue-nginx
    image: nginx
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt # Mount Certbot certificates
      - ./certbot/www:/var/www/certbot  # Certbot challenge directory
    depends_on:
      - vue-app

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt # Mount Certbot certificates
      - ./certbot/www:/var/www/certbot  # Certbot challenge directory
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $!; certbot renew; done;'"
